# Generated by Django 5.1.4 on 2025-11-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_alter_agent_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="token",
            field=models.CharField(
                db_index=True,
                default="a_75260eb4-3975-4b0b-bd74-7f80946a3dd0",
                max_length=255,
                unique=True,
            ),
        ),
    ]
