# Generated by Django 5.1.4 on 2025-11-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_conversation_alter_agent_token_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="token",
            field=models.CharField(
                db_index=True,
                default="a_47468b80-42a2-4b14-90fc-f5f1eff1f9d9",
                max_length=255,
                unique=True,
            ),
        ),
    ]
