# Generated by Django 5.1.4 on 2025-11-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_alter_agent_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="token",
            field=models.CharField(
                db_index=True,
                default="a_fc46f458-9b74-4963-8033-b609b0964b74",
                max_length=255,
                unique=True,
            ),
        ),
    ]
